name: "Web Deploy Action"
description: "Deploy Web application to server via SSH"
branding:
    icon: "upload-cloud" # 从 https://feathericons.com/ 选择一个图标
    color: "blue" # 可选：blue, green, orange, purple, red, yellow

inputs:
    source_dir:
        description: "Directory to build from"
        required: true
        default: "dist"
    deploy_dir:
        description: "Directory to deploy to on the server"
        required: true
    server_key:
        description: "SSH private key for server access"
        required: true
    server_user:
        description: "SSH user for server access"
        required: true
    server_host:
        description: "Server hostname or IP"
        required: true
    node_version:
        description: "Node.js version to use"
        required: true
        default: "18"

runs:
    using: "composite"
    steps:
        - name: Setup SSH
          uses: webfactory/ssh-agent@v0.8.0
          with:
              ssh-private-key: ${{ inputs.server_key }}

        - name: Deploy
          shell: bash
          env:
              SOURCE_DIR: ${{ inputs.source_dir }}
              DEPLOY_USER: ${{ inputs.server_user }}
              DEPLOY_HOST: ${{ inputs.server_host }}
              DEPLOY_DIR: ${{ inputs.deploy_dir }}
          run: |
              # 添加服务器到已知主机
              ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

              # 生成发布目录名
              TIMESTAMP=$(date +%Y%m%d_%H%M%S)
              CODE_DIR="${DEPLOY_DIR}/${TIMESTAMP}"

              # 创建发布目录
              ssh $DEPLOY_USER@$DEPLOY_HOST "mkdir -p ${CODE_DIR}"

              # 复制构建产物
              scp -r ${SOURCE_DIR}/* $DEPLOY_USER@$DEPLOY_HOST:${CODE_DIR}/

              # 修改软链接
              ssh $DEPLOY_USER@$DEPLOY_HOST "ln -sfn ${CODE_DIR} ${DEPLOY_DIR}/current"
